const food = [
  {
    id: 1,
    ime: "Piletina s roštilja",
    kategorija: "Glavna jela",
    cijena: 75.0,
    sastojci: ["piletina", "začini", "maslinovo ulje"],
  },
  {
    id: 2,
    ime: "Bečki odrezak",
    kategorija: "Glavna jela",
    cijena: 70.0,
    sastojci: ["teleći odrezak", "jaja", "krušne mrvice"],
  },
  {
    id: 3,
    ime: "Pasta carbonara",
    kategorija: "Glavna jela",
    cijena: 65.0,
    sastojci: ["špageti", "slanina", "jaja", "parmezan"],
  },
  {
    id: 4,
    ime: "Čokoladni soufflé",
    kategorija: "Deserti",
    cijena: 50.0,
    sastojci: ["čokolada", "jaja", "šećer", "brašno"],
  },
  {
    id: 5,
    ime: "Caprese salata",
    kategorija: "Predjela",
    cijena: 40.0,
    sastojci: ["rajčica", "mozzarella", "bosiljak"],
  },
  {
    id: 6,
    ime: "Bruschetta",
    kategorija: "Predjela",
    cijena: 30.0,
    sastojci: ["kruh", "rajčica", "češnjak", "maslinovo ulje"],
  },
  {
    id: 7,
    ime: "Rižoto s gljivama",
    kategorija: "Glavna jela",
    cijena: 80.0,
    sastojci: ["riža", "gljive", "luk", "pileći temeljac"],
  },
  {
    id: 8,
    ime: "Palačinke s Nutellom",
    kategorija: "Deserti",
    cijena: 45.0,
    sastojci: ["brašno", "jaja", "mlijeko", "Nutella"],
  },
  {
    id: 9,
    ime: "Gazpacho",
    kategorija: "Supe",
    cijena: 35.0,
    sastojci: ["rajčica", "krastavci", "paprika", "češnjak"],
  },
  {
    id: 10,
    ime: "Grčka salata",
    kategorija: "Salate",
    cijena: 40.0,
    sastojci: ["rajčica", "krastavci", "crveni luk", "feta sir"],
  },
  {
    id: 11,
    ime: "Tiramisu",
    kategorija: "Deserti",
    cijena: 55.0,
    sastojci: ["savoiardi", "kava", "mascarpone", "kakao"],
  },
  {
    id: 12,
    ime: "Sushi mix",
    kategorija: "Glavna jela",
    cijena: 120.0,
    sastojci: ["riža", "sirova riba", "alge", "wasabi"],
  },
  {
    id: 13,
    ime: "Krem juha od bundeve",
    kategorija: "Supe",
    cijena: 35.0,
    sastojci: ["bundeva", "vrhnje", "luk", "začini"],
  },
  {
    id: 14,
    ime: "Spaghetti Bolognese",
    kategorija: "Glavna jela",
    cijena: 65.0,
    sastojci: ["špageti", "mljeveno meso", "rajčica", "luk"],
  },
  {
    id: 15,
    ime: "Pizza Margherita",
    kategorija: "Glavna jela",
    cijena: 60.0,
    sastojci: ["tijesto za pizzu", "rajčica", "mozzarella", "bosiljak"],
  },
  {
    id: 16,
    ime: "Cezar salata",
    kategorija: "Salate",
    cijena: 50.0,
    sastojci: ["zeleni salat", "piletina", "krekeri", "parmezan"],
  },
  {
    id: 17,
    ime: "Lasagne",
    kategorija: "Glavna jela",
    cijena: 85.0,
    sastojci: ["tijesto za lasagne", "mljeveno meso", "bešamel", "parmezan"],
  },
  {
    id: 18,
    ime: "Ratatouille",
    kategorija: "Glavna jela",
    cijena: 70.0,
    sastojci: ["patlidžan", "tikvice", "rajčica", "paprika"],
  },
  {
    id: 19,
    ime: "Cheesecake",
    kategorija: "Deserti",
    cijena: 60.0,
    sastojci: ["keksi", "krema od sira", "šećer", "voće"],
  },
  {
    id: 20,
    ime: "Zapečeni grah",
    kategorija: "Glavna jela",
    cijena: 55.0,
    sastojci: ["grah", "luk", "slanina", "paprika"],
  },
  // možete nastaviti s dodavanjem jela prema potrebi...
];

export { food };
